apiVersion: v1
kind: Service
metadata:
  name: java-internship-auth-service
  labels:
    app: java-internship-auth-service
spec:
  selector:
    app: java-internship-auth-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
  